from builtins import str, int
from enum import IntEnum
from typing import Protocol, Sequence

__version__: str

class Suit(IntEnum):
    Hearts: Suit
    Diamonds: Suit
    Clubs: Suit
    Spades: Suit

class Rank(IntEnum):
    Undef: Rank
    Ace: Rank
    Two: Rank
    King: Rank

class Location(IntEnum):
    Waste: Location
    Stock: Location
    Tableau: Location
    Foundation: Location

class MoveKind(IntEnum):
    WasteToStock : MoveKind
    StockToWaste : MoveKind

    WasteToTableau : MoveKind
    WasteToFoundation : MoveKind
    
    TableauToTableau : MoveKind
    TableauToFoundation : MoveKind


class PrintingInterface(Protocol):
    def print(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr(self) -> str: ...

class MoveInterface(PrintingInterface, Protocol):
    def __init__(
        self,
        source: Location = Location.Waste,
        target: Location = Location.Waste,
        source_index: int = 0,
        target_index: int = 0,
        amount: int = 1,
    ) -> None: ...
    def source(self) -> Location: ...
    def target(self) -> Location: ...
    def source_index(self) -> int: ...
    def target_index(self) -> int: ...
    def type(self) -> MoveKind: ...
    def amount(self) -> int: ...
    def __eq__(self, other) -> bool: ...

class BasicMove(MoveInterface): ...
class PackedMove(MoveInterface): ...

class CardInterface(PrintingInterface, Protocol):
    def __init__(self, suit : Suit = Suit.Hearts, rank : Rank = Rank.Undef) -> None : ...
    def suit(self) -> Suit: ...
    def rank(self) -> Rank: ...
    def is_red(self) -> bool: ...
    def is_black(self) -> bool: ...
    def is_valid(self) -> bool: ...
    def can_play_below(self) -> bool: ...
    def __eq__(self, other) -> bool: ...

class BasicCard(CardInterface): ...
class PackedCard(CardInterface): ...

class DeckInterface(PrintingInterface, Protocol):
    def __init__(self) -> None: ...
    def shuffle(self) -> None: ...
    def pick(self) -> None: ...
    def __len__(self) -> None: ...

class Deck(DeckInterface) : ...
class PackedCardDeck(DeckInterface): ...

class GameDeckInterface(Protocol):
    def waste_empty(self) -> bool : ...
    def stock_empty(self) -> bool : ...
    def top_of_waste(self) -> bool : ...
    def size(self) -> int : ...
    def stock_size(self) -> int: ...
    def draw_from_waste(self) -> CardInterface : ...
    def reset_draw(self) -> None: ...
    def mill(self) -> None: ...

class BasicCardBasicGameDeck(GameDeckInterface): ...
class PackedCardBasicGameDeck(GameDeckInterface): ...

class TableauInterface(Protocol):
    def num_face_up(self, index : int) -> int : ...
    def num_face_down(self, index : int) -> int: ...
    def face_up(self, index : int) -> Sequence[CardInterface]: ...
    def move_onto(self, other : Sequence[CardInterface], index: int) -> None: ...
    def take_from(self, num_take : int, index : int) -> Sequence[CardInterface]: ...

class BasicCardBasicTableau(TableauInterface): ...
class PackedCardBasicTableau(TableauInterface): ...

class FoundationInterface(Protocol):
    def at(self, suit : Suit) -> Rank : ...
    def play_onto(self, suit : Suit) -> None : ...

class BasicFoundation(FoundationInterface): ...

class GameBoardInterface(PrintingInterface, Protocol):
    def __init__(self, shuffle: bool = True, seed: int = 0) -> None: ...

    def gamedeck(self) -> GameDeckInterface : ...
    def foundation(self) -> FoundationInterface : ...
    def tableau(self) -> TableauInterface: ...

    def is_valid_move(self, move : MoveInterface) -> bool : ...
    def apply_move(self, move : MoveInterface) -> None : ...

    def reset(self, seed: int = 0) -> None: ...

class BasicGameBoard(GameBoardInterface) : ...

def all_valid_moves(board: BasicGameBoard) -> list[BasicMove]: ...
def all_valid_moves_packed(board: BasicGameBoard) -> list[PackedMove]: ...